development:
  adapter: postgresql
  database: sf_survivor_services_api_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: sf_survivor_services_api_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sf_survivor_services_api_production
  pool: 5
  timeout: 5000